using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.Common.Models
{
    public class FileDto
    {
        public Stream Content { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }

        public string GetPathWithFileName(string basePath) // limit client side file name
        { 
            string uniqueAutoGeneratedFileName = Path.GetRandomFileName();
            string shortClientSideFileNameWithoutExt = Path.GetFileNameWithoutExtension(Name).Substring(0, Math.Min(Path.GetFileNameWithoutExtension(Name).Length, 10));
            string ext = Path.GetExtension(Name);

            return basePath + uniqueAutoGeneratedFileName + '_' + shortClientSideFileNameWithoutExt + ext;
        }
    }
}
